title: SYSU-AERO-SWIFT!!
lang: en
description: we are the best areo team in  current SYSU. 

remote_theme: jekyllrtdtheme/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock